version: '2.3'

networks:
  wordpot_local:

services:

# Wordpot service
  wordpot:
    build: .
    container_name: wordpot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - wordpot_local
    ports:
     - "80:80"
    image: "dtagdevsec/wordpot:2204"
    #    read_only: true
    #    volumes:
            # - /data/wordpot/log:/opt/ddospot/ddospot/db
