version: '2.3'

networks:
  redishoneypot_local:

services:

# redishoneypot service
  redishoneypot:
    build: .
    container_name: redishoneypot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - redishoneypot_local
    ports:
     - "6379:6379"    
    image: "dtagdevsec/redishoneypot:2204"
    read_only: true
    volumes:
     - /data/redishoneypot/log:/var/log/redishoneypot
