version: '2.3'

networks:
  medpot_local:

services:

# medpot service
  medpot:
    build: .
    container_name: medpot
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - medpot_local
    ports:
     - "2575:2575"
    image: "dtagdevsec/medpot:2204"
    read_only: true
    volumes:
     - /data/medpot/log/:/var/log/medpot
