version: '2.3'

networks:
  endlessh_local:

services:

# Endlessh service
  endlessh:
    build: .
    container_name: endlessh
    restart: always
#    cpu_count: 1
#    cpus: 0.25
    networks:
     - endlessh_local
    ports:
     - "22:2222"
    image: "dtagdevsec/endlessh:2204"
    read_only: true
    volumes:
     - /data/endlessh/log:/var/log/endlessh
